#!/bin/bash

# Usage sendgrades NAME EMAIL [OPTIONAL SLEEP]

echo "Sending grades for $1 to $2@grinnell.edu";

grep "^$2" grades | mail -s "CSC151.02 2013F: Grades for $1" -c rebelsky@grinnell.edu $2@grinnell.edu ;

if [ -n "$3" ]; then
  echo "Pausing for $3 seconds.";
  sleep $3;
fi
