#!/bin/sh

rm -f $1.md;
echo "* [Morning EBoard $1](../eboards.am/eboard.$1.html)
  ([Source a.m. $1](../eboards.am/eboard.$1.md))
* [Afternoon EBoard $1](../eboards.pm/eboard.$1.html)
  ([Source p.m. $1](../eboards.pm/eboard.$1.md))" > $1.md;
