#!/usr/bin/perl

# all-outline-parts N
#   Create admin.#.md for each # from 1 to N.

if ($#ARGV != 0) {
  print STDERR "Usage: all-outline-parts N\n";
  exit 1;
}

my $N = shift;

for (my $i = 1; $i <= $N; $i++) {
  $num = twodigits($i);
  system("../tools/outline-parts-blank-md $num");
} # for

sub twodigits()
{
  my $val = shift;
  $val = $val + 0;
  if ($val < 10) { return "0$val"; }
  else { return $val; }
}
    

