#!/usr/bin/perl

# link-sections dir
#   Created soft links to all of the .sect files in dir

$dir = shift;

$FILES = `ls $dir/*.sect`;
@FILES = split /\n/, $FILES;
foreach $path (@FILES) {
  # Get just the file name from the path
  $file = $path;
  $file =~ s/$dir\///;
  # If there is not a link
  if (! -f "./$file") {
    print "Linking $path\n";
    symlink $path, "./$file";
  } # if the file does not exist
  
} # foreach $path
