#!/usr/bin/perl

# link-files dir
#   Created soft links to all of the files in dir

$dir = shift;

$FILES = `ls $dir`;
@FILES = split /\n/, $FILES;
foreach my $file (@FILES) {
  # Add the path
  my $path = "$dir/$file";
  # If there is not a link
  if ((! -e "./$file") && (! -l "./$file")) {
    print "Linking $path\n";
    symlink $path, "./$file";
  } # if the file does not exist
  
} # foreach $path
