#!/usr/bin/perl

# mkoutline NN 
#   Create the outline for date NN. 
#
# Note: 
#   Requires that ../resources/subjects.ent exist and contain an
#   entity for abbrevNN

# +---------+---------------------------------------------------------
# | Globals |
# +---------+

# $NN - The number of the outline (taken from the command line)
my $NN = shift;
$NN = twoDigits($NN);

# $subjects - The file that stores the entites for the daily subjects.
my $subjects = "../resources/subjects.ent";

# $PREFIX - The prefix used for all the files for this day
my $PREFIX;

# $ADMIN - The file that contains the administrivia
my $ADMIN = "admin-$NN.xml";

# +------+------------------------------------------------------------
# | Main |
# +------+

# Sanity check
if (! -f $subjects) {
  print STDERR "Could not find $subjects\n";
  exit 1;
}

# Grab the prefix
$PREFIX = lookup("abbrev$NN", $subjects);
if (! $PREFIX) {
  print STDERR "Could not find abbreviation for $NN in $subjects.\n";
  exit 1;
}

# Create the administrative page (if it doesn't exist)
system("touch $ADMIN");

# Print the start of the page
print <<"TOP";
<section id="outline-$NN"><title>Outline $NN: &title$NN;</title>

<para class="date">&date$NN;</para>

<noprint>
TOP

# Print links to the previous and next pages
print "<para class='foo'>\n";
my $prev = twoDigits($NN - 1);
my $next = twoDigits($NN + 1);
my $prevtitle = lookup("title$prev", $subjects);
my $nexttitle = lookup("title$next", $subjects);
if ($prevtitle) { 
  print "Back to <ulink url=\"outline.$prev.html\">Outline $prev - $prevtitle</ulink>.\n";
}
if ($nexttitle) { 
  print "On to <ulink url=\"outline.$next.html\">Outline $next - $nexttitle</ulink>.\n";
}
print "<\/para>\n\n";

print <<"END_NOPRINT";
</noprint>

END_NOPRINT

my $pre = "<emphasis type=\"strong\">";
my $post = "</emphasis>";

# The three introductory things: Summary, list of related topics, overview
includeOptionalXMLFile("$PREFIX-summary.xml", "${pre}Summary${post}");
includeOptionalXMLFile("$PREFIX-related.xml", "${pre}Related Pages${post}");
includeOptionalXMLFile("$PREFIX-overview.xml", "${pre}Overview${post}");

# Daily notes/administrivia.
includeXMLFile($ADMIN, "${pre}Administrivia${post}");

# And the body
includeOptionalXMLFile("$PREFIX-body.xml");

print <<"BOTTOM";

</section> <!-- outline-$NN -->
BOTTOM

# +-------------+-----------------------------------------------------
# | Subroutines |
# +-------------+

# includeOptionalXMLFile(filename,prelim)
#   Add code to include the file, but only if it exists.  Also includes
#   the prelim
sub includeOptionalXMLFile()
{
  my $file = shift;
  my $prelim = shift;
  if (-f $file) {
    includeXMLFile($file, $prelim);
  }
} # includeOptionalXMLFile

# includeXMLFile(filename,prelim)
#   Add code to include the file
sub includeXMLFile()
{
  my $file = shift;
  my $prelim = shift;
  if ("$prelim") {
    print "$prelim\n";
  }
  print <<"INCLUDE";
<xi:include href="$file" parse="xml" 
  xmlns:xi="http://www.w3.org/2001/XInclude"/>

INCLUDE
} # includeXMLFile
    
# lookup(entity,file)
#   Look up the entity in an entity file.
sub lookup()
{
  my $entity = shift;
  my $file = shift;
  my $result = `grep $entity $file`;
  chomp($result);
  $result =~ s/^[^"]*"//;
  $result =~ s/".*$//;
  return $result;
} # lookup()

# twoDigits(num)
#   Express a number as two (or more) digits)
#   Pre: 0 <= num < 100
sub twoDigits()
{
  my $n = shift;
  $n = $n + 0; # remove leading 0's
  if ($n < 10) {
    return "0$n";
  }
  else {
    return "$n";
  }
} # twoDigits()
