#!/usr/bin/perl

# outline-parts-blank-md prefix-or-number
#   Make empty parts of an outline.

my $prefix = shift;
# If it's a number, get the real prefix
if ($prefix =~ m/[0-9][0-9]/) {
  $prefix = `grep "abbrev$prefix" ../resources/subjects.ent`;
  chomp($prefix);
  $prefix =~ s/^[^"]*"//;
  $prefix =~ s/".*$//;
}

$file = "summaries/$prefix.md";
if (! -f "$file") {
  print STDERR "Creating $file\n";
  system("touch $file");
}

my $file = "overviews/$prefix.md";
if (! -f "$file") {
  print STDERR "Creating $file\n";
  system("touch $file");
}

my $file = "bodies/$prefix.md";
if (! -f "$file") {
  print STDERR "Creating $file\n";
  system("touch $file");
}
